### ISSUE TITLE
[PE-D][Tester A] Reconsider validation criterion for age

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F11-3/tp#294] opened 2024-11-09 00:11 UTC
Understand that the current validation criterion for age is that it should only contain numbers and should be between 1-3 digits long inclusive.

However allowing a user to key in age 999 without a warning (while invalidating user input for other numbers) --- would it be better if 999 is invalidated as well? Perhaps age up to 200 is okay, the scope of the age range can be narrower.

![image.png](https://raw.githubusercontent.com/cth06-Github/ped/main/files/90ada310-de59-4546-bdde-3bb49735ece8.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: cth06-Github/ped#17

**Comment by Jaynon** [comment] 2024-11-09 03:18
duplicate of #225

**Closed as completed by Jaynon** 2024-11-09 03:18 UTC
