### ISSUE TITLE
[PE-D][Tester A] Inputting Names format may be a bit too restrictive

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F11-3/tp#252] opened 2024-11-08 20:27 UTC
Understanding that the app is meant to keep a record of patients for small clinics, thus ensuring **full name** accuracy is perhaps very important,

If patient full names contain special characters such as 

Ravindran S/O Sockalingam
Alastor Tan Tze How (Chen Zi Hao)
Lynette Cheryl Ruth @ Ong Li Jia
Liu Huan, Gladys

How should these names be keyed in if needed? Currently I am unable to. (I am not making up names, these are real full names of people...except for the 2nd version but from what I understand in the ICA website, it's possible). If not allowed, would it be better if the documentation user guide explains?

E.g.
`add n/Ravindran S/O Sockalingam a/36 g/F i/S1234567Q p/98765432 e/johnd@example.com h/311,Clementi Ave 2, #02-25 apt/03/10/1980 18:30 t/O` --> cannot. Esp. for the first example, names in this format is rather common.

![image.png](https://raw.githubusercontent.com/cth06-Github/ped/main/files/14ccdbc2-63be-4260-8ce0-5e958c335af1.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: cth06-Github/ped#6

**Comment by Jaynon** [comment] 2024-11-09 06:00
duplicate of #226

**Closed as completed by Jaynon** 2024-11-09 06:00 UTC
Labels: severity.Medium
