### ISSUE TITLE
[PE-D][Tester C] Empty page in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F11-3/tp#238] opened 2024-11-08 18:44 UTC
Page 7/29 in the UG is a blank page.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: jason-chuah/ped#5

**Comment by Jaynon** [comment] 2024-11-09 02:30
Duplicate of #222

**Closed as completed by Jaynon** 2024-11-09 02:30 UTC
