### ISSUE TITLE
[PE-D][Tester D] Only one appointment for patient at any one point in time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F11-3/tp#240] opened 2024-11-08 19:00 UTC
![image.png](https://raw.githubusercontent.com/yuanchengg/ped/main/files/4e341126-69a8-4144-a91b-2c58dfe24038.png)

Patients can have multiple appointments scheduled for them. Only one appointment can be scheduled for each patient at any point in time.

Steps to reproduce: 
-	Input ‘update T0123456A apt/29/10/2023 14:30’
-	Input ‘update T0123456A apt/30/12/2025 15:40’
-	Input ‘update T0123456A apt/12/01/2024 15:00’

Expected: Patients to have multiple appointments scheduled
Actual: Only one appointment for each patient at any point in time.

Severity: Medium

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: yuanchengg/ped#5

**Comment by Jaynon** [comment] 2024-11-09 02:50
duplicate of #228

**Closed as completed by Jaynon** 2024-11-09 02:50 UTC
Labels: type.Enhancement
