### ISSUE TITLE
[PE-D][Tester A] Spelling error of Prefix for contact number in add command format  in user guide under adding a patient: add section

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F11-3/tp#248] opened 2024-11-08 19:42 UTC
Is the prefix for contact number written wrongly?

![image.png](https://raw.githubusercontent.com/cth06-Github/ped/main/files/24c6797a-8dd9-4950-a26e-7a16f335826b.png)

`p/CONTACT_NUMBER` for adding contact is successful but not `c/CONTACT_NUMBER`

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: cth06-Github/ped#5

**Comment by Jaynon** [comment] 2024-11-09 02:53
duplicate of #242

**Closed as completed by Jaynon** 2024-11-09 02:53 UTC
