### ISSUE TITLE
[PE-D][Tester E] Able to schedule an appointment with a dates that is in the past

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F11-3/tp#263] opened 2024-11-08 21:49 UTC
## Description

It is possible for the user to schedule an appointment with a date that is in the past.

If the user were to accidentally type the wrong year (E.g. `2023` instead of `2024`), the application would still allow the appointment to be scheduled.

This could lead to appointments being missed if the user never realises their error.

I think it would be helpful to add some form of data validation to prevent user errors from causing more issues.

## Reproducing the Bug

Using the command:

`add n/Jason Chan a/36 g/M i/S1234567T p/98765432 e/jasonchan@example.com h/Changi Village apt/09/11/2023 17:30 t/Patient`

allows the user to schedule an appointment for `2023`.

### Screenshots

![past-appt-1.png](https://raw.githubusercontent.com/zackjh/ped/main/files/5b84183d-4412-4824-868c-1e6148040987.png)

![past-appt-2.png](https://raw.githubusercontent.com/zackjh/ped/main/files/10df8191-109e-4082-9971-248f316e628d.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: zackjh/ped#10

**Comment by Jaynon** [comment] 2024-11-09 03:01
duplicate of #245

**Closed as completed by Jaynon** 2024-11-09 03:01 UTC
